//! Fetching the sample disks, so an operator does not have to go and find them.
//!
//! The disks are **not ours** and are never shipped: they are David Hansel's
//! Altair 8800 simulator collection, and the vintage software on them belongs to
//! MITS, Microsoft and Digital Research. What this does is fetch them *on the
//! operator's behalf* from the original repository, which is a different act
//! from redistributing them and is why nothing here is mirrored or bundled.
//!
//! Three rules make the offer honest rather than a lucky dip.
//!
//! **Only disks that are known to run.** The list is generated from this
//! project's own boot survey, not typed out: 29 of the collection's 34 boot and
//! sign on, TDISK04 boots and paints a VDM-1 screen, and the remaining four are
//! deliberately left out — three are data companions with no boot program and
//! one is a blank. Offering those would make the feature a catalogue of
//! disappointments, which is exactly what an operator does not need on their
//! first evening.
//!
//! **Pinned, so what arrives is what was tested.** The URL names a commit, not
//! a branch. Upstream's `disks/` folder last changed in September 2020, so this
//! is stable — but a pin is what makes "known to run" keep meaning something
//! rather than quietly rotting the way a stale readme does.
//!
//! **Verified, so a changed file is caught rather than accepted.** Every disk
//! carries the SHA-256 of the bytes the pinned URL really served when the
//! manifest was generated, checked again on arrival. A mismatch is refused and
//! reported; it is not written to disk.
//!
//! And nothing already in the images folder is ever overwritten. An operator
//! who has edited a disk, or put their own there under the same name, keeps it.

use std::path::Path;

/// The commit the manifest was generated from and the downloads are pinned to.
///
/// A commit rather than `master`: the point of the manifest is that these exact
/// bytes were booted and surveyed, and a branch name would let upstream change
/// what "verified" refers to.
pub const ALTAIR_DUINO_COMMIT: &str = "3a42f6646c193567f1c9859c3fa1d06126088490";

/// Where the collection comes from, for the operator to see before agreeing.
pub const ALTAIR_DUINO_SOURCE: &str = "github.com/dhansel/Altair8800";

/// One disk in the catalogue.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Disk {
    /// The filename, which is also the name it takes in the images folder.
    pub name: String,
    /// Size in bytes, as served.
    pub bytes: u64,
    /// SHA-256 of the bytes the pinned URL served when this was generated.
    pub sha256: String,
    /// What it is, in a few words, for the operator choosing whether to bother.
    pub note: String,
}

impl Disk {
    /// Where this disk is fetched from.
    pub fn url(&self) -> String {
        format!(
            "https://raw.githubusercontent.com/dhansel/Altair8800/{}/disks/{}",
            ALTAIR_DUINO_COMMIT, self.name
        )
    }
}

/// The manifest, generated by `record_altairduino_manifest` from the disks this
/// project has actually booted.
fn manifest_text() -> &'static str {
    include_str!("altairduino.txt")
}

/// Every disk on offer.
///
/// Parsed rather than compiled in as a literal so the generated file stays
/// readable and reviewable in a diff — the same choice as `repodisks.txt`. A
/// malformed line is skipped rather than fatal: a catalogue that refuses to
/// load at all would cost the operator the whole feature over one bad row, and
/// [`test_the_manifest_parses_completely`] is what stops that happening
/// silently.
pub fn catalogue() -> Vec<Disk> {
    manifest_text()
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .filter_map(|line| {
            let mut f = line.split('\t');
            let name = f.next()?.trim().to_string();
            let bytes = f.next()?.trim().parse().ok()?;
            let sha256 = f.next()?.trim().to_string();
            let note = f.next().unwrap_or("").trim().to_string();
            (!name.is_empty() && sha256.len() == 64).then_some(Disk { name, bytes, sha256, note })
        })
        .collect()
}

/// The disks not already in the images folder.
///
/// **Never overwrites.** A file already there is the operator's — they may have
/// edited it, or put their own disk under that name — so it is left exactly as
/// it is and reported as already present rather than replaced.
pub fn missing(images: &Path, all: &[Disk]) -> Vec<Disk> {
    all.iter().filter(|d| !images.join(&d.name).exists()).cloned().collect()
}

/// How a download ended.
#[derive(Default, Debug, PartialEq, Eq)]
pub struct Report {
    /// Disks written to the images folder.
    pub fetched: Vec<String>,
    /// Disks already present, left untouched.
    pub skipped: Vec<String>,
    /// Disks that could not be had, and why.
    pub failed: Vec<(String, String)>,
}

impl Report {
    /// One line an operator can read on any of the three interfaces.
    pub fn summary(&self) -> String {
        let mut parts = Vec::new();
        if !self.fetched.is_empty() {
            parts.push(format!("{} downloaded", self.fetched.len()));
        }
        if !self.skipped.is_empty() {
            parts.push(format!("{} already there", self.skipped.len()));
        }
        if !self.failed.is_empty() {
            parts.push(format!("{} failed", self.failed.len()));
        }
        if parts.is_empty() {
            return "Nothing to do.".to_string();
        }
        parts.join(", ")
    }
}

/// SHA-256, for verifying what arrived is what was tested.
///
/// Written out rather than pulled in: this is the only hash this crate needs,
/// a dependency for it would be a supply-chain decision taken for one function,
/// and the algorithm is fixed for ever by its own specification.
fn sha256(data: &[u8]) -> String {
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
        0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
        0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
        0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
        0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
        0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
        0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
        0xc67178f2,
    ];
    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
        0x5be0cd19,
    ];
    let mut msg = data.to_vec();
    let bits = (data.len() as u64) * 8;
    msg.push(0x80);
    while msg.len() % 64 != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&bits.to_be_bytes());

    for chunk in msg.chunks(64) {
        let mut w = [0u32; 64];
        for (i, word) in w.iter_mut().enumerate().take(16) {
            let b = &chunk[i * 4..i * 4 + 4];
            *word = u32::from_be_bytes([b[0], b[1], b[2], b[3]]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }
        let (mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh) =
            (h[0], h[1], h[2], h[3], h[4], h[5], h[6], h[7]);
        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ ((!e) & g);
            let t1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }
        for (slot, v) in h.iter_mut().zip([a, b, c, d, e, f, g, hh]) {
            *slot = slot.wrapping_add(v);
        }
    }
    h.iter().map(|w| format!("{w:08x}")).collect()
}

/// Fetch one disk and verify it, returning its bytes.
///
/// Verification is not a formality: the whole claim of this feature is that
/// these exact bytes were booted, so a file that arrives different is refused
/// rather than written. A truncated download and a changed upstream both land
/// here, and both should stop.
fn fetch_one(disk: &Disk) -> Result<Vec<u8>, String> {
    let agent = ureq::Agent::new_with_config(
        ureq::config::Config::builder()
            .timeout_global(Some(std::time::Duration::from_secs(120)))
            .build(),
    );
    let mut resp = agent
        .get(&disk.url())
        .header("User-Agent", "EthernetGateway (CP/M sample disks)")
        .call()
        .map_err(|e| format!("{e}"))?;
    if resp.status().as_u16() != 200 {
        return Err(format!("HTTP {}", resp.status().as_u16()));
    }
    let body = resp
        .body_mut()
        .with_config()
        .limit(64 << 20)
        .read_to_vec()
        .map_err(|e| format!("{e}"))?;
    if body.len() as u64 != disk.bytes {
        return Err(format!("expected {} bytes, got {}", disk.bytes, body.len()));
    }
    let got = sha256(&body);
    if got != disk.sha256 {
        return Err(format!("checksum mismatch (got {}…)", &got[..12]));
    }
    Ok(body)
}

/// Fetch every disk that is not already there.
///
/// `progress` is called before each download with the name and the position in
/// the run, so a caller can say something on a screen that is about to be quiet
/// for a minute. Failures do not stop the run: one unavailable disk should not
/// cost the operator the other twenty-nine.
pub fn download_missing(
    images: &Path,
    mut progress: impl FnMut(&str, usize, usize),
) -> Result<Report, String> {
    std::fs::create_dir_all(images).map_err(|e| format!("{}: {e}", images.display()))?;
    let all = catalogue();
    let mut report = Report::default();
    let wanted = missing(images, &all);
    for d in &all {
        if !wanted.iter().any(|w| w.name == d.name) {
            report.skipped.push(d.name.clone());
        }
    }
    let total = wanted.len();
    for (i, disk) in wanted.iter().enumerate() {
        progress(&disk.name, i + 1, total);
        match fetch_one(disk) {
            Ok(bytes) => {
                // Written to a temporary name and renamed, so an interrupted
                // download cannot leave a half a disk image behind under a name
                // the rest of the gateway will then try to mount.
                let tmp = images.join(format!("{}.part", disk.name));
                let done = images.join(&disk.name);
                match std::fs::write(&tmp, &bytes).and_then(|_| std::fs::rename(&tmp, &done)) {
                    Ok(()) => report.fetched.push(disk.name.clone()),
                    Err(e) => {
                        let _ = std::fs::remove_file(&tmp);
                        report.failed.push((disk.name.clone(), format!("{e}")));
                    }
                }
            }
            Err(e) => report.failed.push((disk.name.clone(), e)),
        }
    }
    Ok(report)
}

#[cfg(test)]
mod generate {
    //! Building `altairduino.txt` from the disks this project has booted.
    //!
    //! Generated, never typed: the whole claim is that these exact bytes were
    //! surveyed, and a hand-kept list drifts from the survey the first time a
    //! disk changes category.

    use super::*;

    /// Regenerate the manifest.
    ///
    /// Ignored: it needs the local collection *and* the network. It downloads
    /// every candidate from the pinned URL and requires the bytes to match the
    /// local copy this project actually booted — so the manifest records what
    /// the URL really serves, verified against what was tested, rather than a
    /// hash of a local file nobody checked was the same.
    ///
    /// Set `ALTAIR_DISKS` to the collection (default
    /// `$HOME/AltairRepos/Altair8800/disks`).
    #[test]
    #[ignore]
    fn record_altairduino_manifest() {
        let dir = std::env::var("ALTAIR_DISKS").unwrap_or_else(|_| {
            format!("{}/AltairRepos/Altair8800/disks", std::env::var("HOME").unwrap())
        });
        let dir = std::path::Path::new(&dir);

        // What the boot survey found. Written here rather than re-run because
        // the survey is a separate, slow gate; these are its results and the
        // test below pins the exclusions so the two cannot silently disagree.
        let refused = ["DISK0B.DSK", "DISK0D.DSK", "DISK0F.DSK", "TDISK06.DSK"];

        let mut names: Vec<String> = std::fs::read_dir(dir)
            .expect("the collection")
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().to_string())
            .filter(|n| n.to_ascii_uppercase().ends_with(".DSK"))
            .filter(|n| !refused.contains(&n.as_str()))
            .collect();
        names.sort();

        let mut out = String::new();
        // Built line by line: a `\`-continued literal keeps the source's own
        // indentation in the output, which put six spaces in front of every
        // comment line the first time.
        for line in [
            "# Altair-Duino sample disks that this gateway is known to run.".to_string(),
            "#".to_string(),
            "# Generated by `record_altairduino_manifest` from the boot survey -- do not".to_string(),
            "# edit by hand.  Each line is NAME<TAB>BYTES<TAB>SHA256<TAB>NOTE, and the hash".to_string(),
            "# is of the bytes the pinned URL really served, checked against the local copy".to_string(),
            "# this project booted.".to_string(),
            "#".to_string(),
            format!("# Source: {ALTAIR_DUINO_SOURCE}"),
            format!("# Pinned at: {ALTAIR_DUINO_COMMIT}"),
            "#".to_string(),
            "# The disks are not ours and are not shipped -- this fetches them from the".to_string(),
            "# original repository on the operator's behalf.  The vintage software on them".to_string(),
            "# belongs to MITS, Microsoft and Digital Research.".to_string(),
            "#".to_string(),
            "# Deliberately NOT offered, because they do not run: DISK0B, DISK0D and DISK0F".to_string(),
            "# are data companions of disks that do boot and carry no boot program; TDISK06".to_string(),
            "# is a blank.  Offering them would make this a catalogue of disappointments.".to_string(),
            "#".to_string(),
        ] {
            out.push_str(&line);
            out.push('\n');
        }

        for name in &names {
            let local = std::fs::read(dir.join(name)).expect("readable");
            let disk = Disk {
                name: name.clone(),
                bytes: local.len() as u64,
                sha256: sha256(&local),
                note: String::new(),
            };
            let served = fetch_one(&Disk { sha256: sha256(&local), ..disk.clone() })
                .unwrap_or_else(|e| panic!("{name}: {e}"));
            assert_eq!(
                sha256(&served),
                disk.sha256,
                "{name}: the pinned URL serves different bytes from the copy that was booted"
            );
            out.push_str(&format!(
                "{}\t{}\t{}\t{}\n",
                disk.name,
                disk.bytes,
                disk.sha256,
                describe(&disk.name)
            ));
            eprintln!("  verified {} ({} bytes)", disk.name, disk.bytes);
        }
        std::fs::write("src/cpm/altairduino.txt", &out).expect("write");
        eprintln!("wrote src/cpm/altairduino.txt: {} disks", names.len());
    }

    /// A few words per disk, so the operator choosing whether to download knows
    /// what they are getting. Families rather than one line each: the survey
    /// knows what boots, not what it is, and inventing a description per disk
    /// would be exactly the hand-written drift this generator avoids.
    fn describe(name: &str) -> &'static str {
        match name {
            "TDISK04.DSK" => "CP/M 1.4 for the VDM-1 - paints the Disk Screen page, not the terminal",
            n if n.starts_with("HDSK") => "Altair 88-HDSK hard disk, 4.9 MB",
            n if n.starts_with("CDISK") => "Cromemco 4FDC/16FDC floppy - CDOS or CP/M 2.2",
            n if n.starts_with("TDISK") => "Tarbell 1011 floppy - CP/M",
            _ => "MITS Altair 88-DCDD floppy - CP/M, DOS or BASIC",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The catalogue is generated, so what matters is that every row survives
    /// the parse — a row silently dropped is a disk quietly missing from the
    /// offer, and nothing else would notice.
    #[test]
    fn test_the_manifest_parses_completely() {
        let rows = manifest_text()
            .lines()
            .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
            .count();
        let disks = catalogue();
        assert_eq!(disks.len(), rows, "a manifest row failed to parse");
        assert!(disks.len() >= 30, "the whole verified collection: got {}", disks.len());
    }

    /// Every entry has to be usable: a name, a real size, and a full hash.
    #[test]
    fn test_every_disk_is_completely_described() {
        for d in catalogue() {
            assert!(d.name.to_ascii_uppercase().ends_with(".DSK"), "{d:?}");
            assert!(d.bytes > 0, "{d:?}");
            assert_eq!(d.sha256.len(), 64, "{d:?}");
            assert!(d.sha256.chars().all(|c| c.is_ascii_hexdigit()), "{d:?}");
            assert!(!d.note.is_empty(), "{} has nothing to tell the operator", d.name);
        }
    }

    /// **The disks that do not work are not on offer.** Three data companions
    /// with no boot program and one blank: downloading those and finding they
    /// do nothing is the disappointment this feature exists to avoid.
    #[test]
    fn test_the_disks_that_do_not_run_are_not_offered() {
        let names: Vec<String> = catalogue().into_iter().map(|d| d.name).collect();
        for refused in ["DISK0B.DSK", "DISK0D.DSK", "DISK0F.DSK", "TDISK06.DSK"] {
            assert!(!names.contains(&refused.to_string()), "{refused} does not boot");
        }
        // And the one that boots to a screen rather than a port *is* offered —
        // it works, it just needs the Disk Screen page to be seen.
        assert!(names.contains(&"TDISK04.DSK".to_string()));
    }

    /// Pinned to a commit, never a branch: "known to run" refers to particular
    /// bytes, and a branch would let upstream change what that means.
    #[test]
    fn test_downloads_are_pinned_to_a_commit() {
        let d = &catalogue()[0];
        assert!(d.url().contains(ALTAIR_DUINO_COMMIT));
        assert!(!d.url().contains("/master/"), "a branch is not a pin: {}", d.url());
        assert!(d.url().starts_with("https://"), "{}", d.url());
    }

    /// **A file already in the images folder is never a candidate.** The
    /// operator may have edited it or put their own there under that name.
    #[test]
    fn test_an_existing_disk_is_never_overwritten() {
        let dir = std::env::temp_dir().join(format!("egfetch{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let all = catalogue();
        assert_eq!(missing(&dir, &all).len(), all.len(), "an empty folder wants them all");

        let mine = dir.join(&all[0].name);
        std::fs::write(&mine, b"my own disk").unwrap();
        let after = missing(&dir, &all);
        assert_eq!(after.len(), all.len() - 1);
        assert!(!after.iter().any(|d| d.name == all[0].name), "it is already there");
        assert_eq!(std::fs::read(&mine).unwrap(), b"my own disk", "and untouched");
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The hash is the whole verification, so it is pinned against the
    /// specification's own vectors rather than trusted.
    #[test]
    fn test_sha256_against_the_published_vectors() {
        assert_eq!(
            sha256(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            sha256(b"abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        assert_eq!(
            sha256(b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
            "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"
        );
        // A block-boundary case, where the padding rule is easiest to get wrong.
        assert_eq!(
            sha256(&[b'a'; 64]),
            "ffe054fe7ae0cb6dc65c3af9b61d5209f439851db43d0ba5997337df154668eb"
        );
    }

    /// **The real thing, end to end**: fetch every disk from the pinned URLs
    /// into an empty folder, verify each against its recorded hash, then run it
    /// again and watch it touch nothing.
    ///
    /// Ignored: it needs the network and moves 17 MB.
    #[test]
    #[ignore]
    fn test_fetch_the_collection_for_real() {
        let dir = std::env::temp_dir().join(format!("egfetchlive{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);

        let first = download_missing(&dir, |name, i, n| eprintln!("  {i}/{n} {name}"))
            .expect("the download runs");
        assert!(first.failed.is_empty(), "{:?}", first.failed);
        assert_eq!(first.fetched.len(), catalogue().len(), "all of them");
        assert!(first.skipped.is_empty(), "the folder was empty");

        // Every file is the size the manifest promised, on disk.
        for d in catalogue() {
            let got = std::fs::metadata(dir.join(&d.name)).expect(&d.name).len();
            assert_eq!(got, d.bytes, "{}", d.name);
        }

        // Run again: nothing is re-fetched and nothing is rewritten.
        let before = std::fs::metadata(dir.join(&catalogue()[0].name)).unwrap().modified().unwrap();
        let second = download_missing(&dir, |_, _, _| {}).expect("the second run");
        assert!(second.fetched.is_empty(), "nothing left to fetch");
        assert_eq!(second.skipped.len(), catalogue().len());
        let after = std::fs::metadata(dir.join(&catalogue()[0].name)).unwrap().modified().unwrap();
        assert_eq!(before, after, "an existing disk was rewritten");

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// **Every disk we offer must actually boot, from the bytes the source
    /// serves.**
    ///
    /// The whole promise of this feature is "known to run", and until now that
    /// rested on a survey of a *local* checkout plus the belief that the URL
    /// serves the same thing. This downloads them and boots each one, so the
    /// claim is tested end to end against the source an operator will use.
    ///
    /// `TDISK04` is the one exception and it is in the manifest deliberately:
    /// it boots and paints a VDM-1 screen instead of writing to a console port,
    /// so it produces no console output by design. Its note says so.
    ///
    /// Ignored: needs the network, and boots thirty machines.
    #[test]
    #[ignore]
    fn test_every_offered_disk_boots_when_downloaded() {
        use crate::cpm::boot_machine::BootMachine;
        let dir = std::env::temp_dir().join(format!("egboots{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let report = download_missing(&dir, |_, _, _| {}).expect("the download runs");
        assert!(report.failed.is_empty(), "{:?}", report.failed);

        let mut silent = Vec::new();
        for disk in catalogue() {
            let bytes = std::fs::read(dir.join(&disk.name)).expect(&disk.name);
            let (machine, _) =
                crate::cpm::detect::machine_for(crate::cpm::console::AUTO_MACHINE, &bytes);
            let mut m = BootMachine::new();
            m.set_machine(&machine);
            m.insert(0, bytes, true).unwrap_or_else(|e| panic!("{}: {e}", disk.name));
            let mut cpu = BootMachine::new_cpu();
            m.boot(&mut cpu, 0).unwrap_or_else(|e| panic!("{}: {e}", disk.name));
            let mut out = Vec::new();
            for _ in 0..20_000_000u64 {
                m.step(&mut cpu);
                out.extend(m.take_output());
                if out.len() > 40 {
                    break;
                }
            }
            if out.is_empty() {
                silent.push(disk.name.clone());
            }
            eprintln!("  {:<14} {}", disk.name, if out.is_empty() { "(silent)" } else { "spoke" });
        }
        assert_eq!(
            silent,
            vec!["TDISK04.DSK".to_string()],
            "a disk we recommend did not boot — the manifest is promising something untrue"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_the_report_says_what_happened() {
        let mut r = Report::default();
        assert_eq!(r.summary(), "Nothing to do.");
        r.fetched.push("A".into());
        r.skipped.push("B".into());
        r.failed.push(("C".into(), "boom".into()));
        assert_eq!(r.summary(), "1 downloaded, 1 already there, 1 failed");
    }
}
