#!/usr/bin/env bash
# Live peer-dial smoke test.  Wires two socat PTY pairs to a headless gateway's
# Port A and Port B, then drives an end-to-end peer-dial call with driver.py.
#
#   ./run.sh            # modem <-> modem (ring + ATA + data + self-dial + no-answer)
#   ./run.sh console    # modem -> console (direct connect + data)
#
# Env: GATEWAY_BIN overrides the binary (default: the repo debug build).
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
BIN="${GATEWAY_BIN:-/home/ricky/xmodem/target/debug/ethernetgateway}"
MODE="${1:-modem}"
WORK="$HERE/work"

command -v socat >/dev/null || { echo "socat not found"; exit 2; }
[ -x "$BIN" ] || { echo "gateway binary not found/executable: $BIN (run: cargo build)"; exit 2; }

cleanup() {
    [ -n "${GW_PID:-}" ] && kill "$GW_PID" 2>/dev/null
    [ -n "${SOCA:-}" ] && kill "$SOCA" 2>/dev/null
    [ -n "${SOCB:-}" ] && kill "$SOCB" 2>/dev/null
}
trap cleanup EXIT

rm -rf "$WORK"; mkdir -p "$WORK"

# One PTY pair per port: <port>_gw is the gateway side, <port>_dev the device side.
socat pty,raw,echo=0,link="$WORK/ttyA_gw" pty,raw,echo=0,link="$WORK/ttyA_dev" &>"$WORK/socatA.log" &
SOCA=$!
socat pty,raw,echo=0,link="$WORK/ttyB_gw" pty,raw,echo=0,link="$WORK/ttyB_dev" &>"$WORK/socatB.log" &
SOCB=$!

# Wait for all four symlinks to appear.
for _ in $(seq 1 50); do
    [ -e "$WORK/ttyA_gw" ] && [ -e "$WORK/ttyA_dev" ] && \
    [ -e "$WORK/ttyB_gw" ] && [ -e "$WORK/ttyB_dev" ] && break
    sleep 0.1
done

BMODE=modem; [ "$MODE" = console ] && BMODE=console

cat > "$WORK/egateway.conf" <<CONF
# Headless peer-dial smoke config (generated by run.sh)
enable_console = false
telnet_enabled = false
ssh_enabled = false
web_enabled = false
gateway_role = standalone
allow_peer_dial = true
serial_a_enabled = true
serial_a_mode = modem
serial_a_port = $WORK/ttyA_gw
serial_a_baud = 9600
serial_b_enabled = true
serial_b_mode = $BMODE
serial_b_port = $WORK/ttyB_gw
serial_b_baud = 9600
CONF

echo "== launching gateway ($MODE mode, Port B = $BMODE) =="
( cd "$WORK" && setsid "$BIN" ) &>"$WORK/gateway.log" &
GW_PID=$!

# Give the two serial-manager threads time to open their PTYs.
sleep 2.5

echo "== driving scenario =="
python3 "$HERE/driver.py" --mode "$MODE" --dev-a "$WORK/ttyA_dev" --dev-b "$WORK/ttyB_dev"
RC=$?

echo
echo "== gateway log (tail) =="
tail -n 25 "$WORK/gateway.log" 2>/dev/null

exit $RC
