#!/usr/bin/env bash
# Live peer-to-peer FILE TRANSFER smoke test.
#
# The peer-dial smoke test proves the bridge carries bytes.  This one runs a
# real sender and a real receiver at the two ends of that bridge and compares
# the file, because a bridge is a **pipe** and the gateway's own notes say a
# pipe carrying a transfer is where translation becomes corruption.
#
#   ./run.sh              # every protocol
#   ./run.sh zmodem       # just one
#
# Env: GATEWAY_BIN overrides the binary; BAUD overrides 9600; SIZE the payload.
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
BIN="${GATEWAY_BIN:-/home/ricky/xmodem/target/debug/ethernetgateway}"
ONLY="${1:-}"
BAUD="${BAUD:-9600}"
SIZE="${SIZE:-8192}"
WORK="$HERE/work"

command -v socat >/dev/null || { echo "socat not found"; exit 2; }
[ -x "$BIN" ] || { echo "gateway binary not found: $BIN (run: cargo build)"; exit 2; }

cleanup() {
    [ -n "${GW_PID:-}" ] && kill "$GW_PID" 2>/dev/null
    [ -n "${SOCA:-}" ] && kill "$SOCA" 2>/dev/null
    [ -n "${SOCB:-}" ] && kill "$SOCB" 2>/dev/null
}
trap cleanup EXIT

rm -rf "$WORK"; mkdir -p "$WORK"

socat pty,raw,echo=0,link="$WORK/ttyA_gw" pty,raw,echo=0,link="$WORK/ttyA_dev" &>"$WORK/socatA.log" &
SOCA=$!
socat pty,raw,echo=0,link="$WORK/ttyB_gw" pty,raw,echo=0,link="$WORK/ttyB_dev" &>"$WORK/socatB.log" &
SOCB=$!

for _ in $(seq 1 50); do
    [ -e "$WORK/ttyA_gw" ] && [ -e "$WORK/ttyA_dev" ] && \
    [ -e "$WORK/ttyB_gw" ] && [ -e "$WORK/ttyB_dev" ] && break
    sleep 0.1
done

mkdir -p "$WORK/ethernetgateway-data"
cat > "$WORK/ethernetgateway-data/egateway.conf" <<CONF
# Headless peer-to-peer transfer smoke config (generated by run.sh)
enable_console = false
telnet_enabled = false
ssh_enabled = false
web_enabled = false
gateway_role = standalone
allow_peer_dial = true
serial_a_enabled = true
serial_a_mode = modem
serial_a_port = $WORK/ttyA_gw
serial_a_baud = $BAUD
serial_b_enabled = true
serial_b_mode = modem
serial_b_port = $WORK/ttyB_gw
serial_b_baud = $BAUD
CONF

echo "== launching gateway (both ports modem, $BAUD baud) =="
( cd "$WORK" && setsid "$BIN" ) &>"$WORK/gateway.log" &
GW_PID=$!
sleep 2.5

echo "== driving transfers ($SIZE-byte payload) =="
ARGS=(--dev-a "$WORK/ttyA_dev" --dev-b "$WORK/ttyB_dev" --work "$WORK" --size "$SIZE")
[ -n "$ONLY" ] && ARGS+=(--only "$ONLY")
python3 "$HERE/driver.py" "${ARGS[@]}"
RC=$?

echo
echo "== gateway log (tail) =="
tail -n 20 "$WORK/gateway.log" 2>/dev/null

exit $RC
