#!/usr/bin/env bash
# Transfers to and from the gateway through its own telnet menu.
#
# The gates in src/ run our codec against a real lrzsz peer, which proves the
# protocol code.  This proves the *product*: the menu, the file picker, the
# protocol chooser and the session's byte path, driven exactly as a user
# drives them, with a real sx/rx/sb/rb/sz/rz on the other end of the socket.
#
#   ./run.sh            # every direction of every protocol
#   ./run.sh zmodem     # just one
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
BIN="${GATEWAY_BIN:-/home/ricky/xmodem/target/debug/ethernetgateway}"
PORT="${PORT:-2397}"
SIZE="${SIZE:-4096}"
ONLY="${1:-}"
WORK="$HERE/work"

[ -x "$BIN" ] || { echo "gateway binary not found: $BIN (run: cargo build)"; exit 2; }
cleanup() { [ -n "${GW_PID:-}" ] && kill "$GW_PID" 2>/dev/null; }
trap cleanup EXIT

rm -rf "$WORK"; mkdir -p "$WORK/xfer" "$WORK/ethernetgateway-data"
cat > "$WORK/ethernetgateway-data/egateway.conf" <<CONF
# Headless telnet transfer smoke config (generated by run.sh)
enable_console = false
telnet_enabled = true
telnet_port = $PORT
ssh_enabled = false
web_enabled = false
security_enabled = false
gateway_role = standalone
serial_a_enabled = false
serial_b_enabled = false
cpm_emu_enabled = false
transfer_dir = $WORK/xfer
verbose = true
CONF

echo "== launching gateway (telnet on $PORT) =="
( cd "$WORK" && setsid "$BIN" ) &>"$WORK/gateway.log" &
GW_PID=$!
for _ in $(seq 1 60); do
    (echo >/dev/tcp/127.0.0.1/$PORT) &>/dev/null && break
    sleep 0.25
done

echo "== driving the menu ($SIZE-byte payload) =="
ARGS=(--port "$PORT" --xferdir "$WORK/xfer" --work "$WORK" --size "$SIZE")
[ -n "$ONLY" ] && ARGS+=(--only "$ONLY")
python3 "$HERE/driver.py" "${ARGS[@]}"
RC=$?
echo; echo "== gateway log (tail) =="; tail -n 15 "$WORK/gateway.log" 2>/dev/null
exit $RC
